DEFAULT_NUMBER_OF_GAMWEEKS_TO_PREDICT = 5
FIXTURE_DIFFICULTY_RATINGS_FILEPATH = "fixture_difficulty_ratings.json"
MAX_GAMEWEEKS = 38


POINTS_PER_GOAL_FORWARD = 4
POINTS_PER_GOAL_MIDFIELDER = 5
POINTS_PER_GOAL_DEFENDER = 6
POINTS_PER_GOAL_GOALKEEPER = 6

POINTS_PER_ASSIST_FORWARD = 3
POINTS_PER_ASSIST_MIDFIELDER = 3
POINTS_PER_ASSIST_DEFENDER = 3
POINTS_PER_ASSIST_GOALKEEPER = 3


POINTS_PER_CLEAN_SHEET_GOALKEEPER = 4
POINTS_PER_CLEAN_SHEET_DEFENDER = 4
POINTS_PER_CLEAN_SHEET_MIDFIELDER = 1
POINTS_PER_CLEAN_SHEET_FORWARD = 0
